# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Prefecture
Prefecture.create!(code: "01", name: "北海道")
Prefecture.create!(code: "02", name: "青森県")
Prefecture.create!(code: "03", name: "岩手県")
Prefecture.create!(code: "04", name: "宮城県")
Prefecture.create!(code: "05", name: "秋田県")
Prefecture.create!(code: "06", name: "山形県")
Prefecture.create!(code: "07", name: "福島県")
Prefecture.create!(code: "08", name: "茨城県")
Prefecture.create!(code: "09", name: "栃木県")
Prefecture.create!(code: "10", name: "群馬県")
Prefecture.create!(code: "11", name: "埼玉県")
Prefecture.create!(code: "12", name: "千葉県")
Prefecture.create!(code: "13", name: "東京都")
Prefecture.create!(code: "14", name: "神奈川県")
Prefecture.create!(code: "15", name: "新潟県")
Prefecture.create!(code: "16", name: "富山県")
Prefecture.create!(code: "17", name: "石川県")
Prefecture.create!(code: "18", name: "福井県")
Prefecture.create!(code: "19", name: "山梨県")
Prefecture.create!(code: "20", name: "長野県")
Prefecture.create!(code: "21", name: "岐阜県")
Prefecture.create!(code: "22", name: "静岡県")
Prefecture.create!(code: "23", name: "愛知県")
Prefecture.create!(code: "24", name: "三重県")
Prefecture.create!(code: "25", name: "滋賀県")
Prefecture.create!(code: "26", name: "京都府")
Prefecture.create!(code: "27", name: "大阪府")
Prefecture.create!(code: "28", name: "兵庫県")
Prefecture.create!(code: "29", name: "奈良県")
Prefecture.create!(code: "30", name: "和歌山県")
Prefecture.create!(code: "31", name: "鳥取県")
Prefecture.create!(code: "32", name: "島根県")
Prefecture.create!(code: "33", name: "岡山県")
Prefecture.create!(code: "34", name: "広島県")
Prefecture.create!(code: "35", name: "山口県")
Prefecture.create!(code: "36", name: "徳島県")
Prefecture.create!(code: "37", name: "香川県")
Prefecture.create!(code: "38", name: "愛媛県")
Prefecture.create!(code: "39", name: "高知県")
Prefecture.create!(code: "40", name: "福岡県")
Prefecture.create!(code: "41", name: "佐賀県")
Prefecture.create!(code: "42", name: "長崎県")
Prefecture.create!(code: "43", name: "熊本県")
Prefecture.create!(code: "44", name: "大分県")
Prefecture.create!(code: "45", name: "宮崎県")
Prefecture.create!(code: "46", name: "鹿児島県")
Prefecture.create!(code: "47", name: "沖縄県")

